name: Push release
on:
  push:
    branches:
      - 'release/**'

jobs:
  push-develop:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup git config
        run: |
          # setup the username and email.
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"

      - name: Merge release branch into develop
        id: merge-develop
        run: |
          git fetch 'origin'
          git switch develop
          git merge $GITHUB_REF --ff -m 'merge $GITHUB_REF into develop'
          git push origin develop